### ISSUE TITLE
What version of Kubernetes and/or OpenShift to target?

### ISSUE THREAD

**Issue by jroper** [lightbend/openshift-deployment-guide#23]
This is pertinent as it impacts which `apiVersion` we target. For example, `apps/v1` has existed since Kubernetes 1.9, but right now the guide is still using `apps/v1beta2`.

**Comment by jroper** [comment]
As far as I can tell, the first OpenShift release to contain at least Kubernetes 1.9 is OpenShift 3.10 (which actually used Kubernetes 1.10). So, if we decide to use `apps/v1`, then we're requiring a minimum OpenShift version of 3.10.

**Comment by TimMoore** [comment]
We don't have great data to drive this decision yet, so for the first pass I'd say "whatever's easiest" which I expect would be OpenShift 3.11/Kubernetes 1.11.

OpenShift 3.x versions sync the minor version so Kubernetes 1.x versions, so OpenShift 3.9 had Kubernetes 1.9.

https://docs.openshift.com/container-platform/3.9/architecture/infrastructure_components/kubernetes_infrastructure.html

**Comment by jroper** [comment]
Fair enough. I'll use `apps/v1`.
