### ISSUE TITLE
Write Lagom 1.5.x-only guide

### ISSUE THREAD

**Issue by ignasi35** [lightbend/openshift-deployment-guide#29]
The guide is currently written from a Lagom 1.4.11 point of view. In particular, it requires adding a few dependencies which are transitive in lagom 1.5.0:

https://developer.lightbend.com/guides/openshift-deployment/lagom/forming-a-cluster.html#adding-cluster-bootstrap-to-your-application

Lagom 1.4.x is still supported by `sbt-native-packager` so we could drop support for Lagom 1.4.x on the guide and the `shopping-cart-xxx` sample apps. If not, the guide will need version-specific details.

**Comment by ignasi35** [comment]
Update: there are a few paragraphs or sections in https://developer.lightbend.com/guides/openshift-deployment/lagom/forming-a-cluster.html that will become obsolete in Lagom 1.5.0

**Comment by ignasi35** [comment]
Best will probably to have split pages for Lagom 1.4.x and Lagom 1.5.x.

There's a lot of content on the [current write-up](https://developer.lightbend.com/guides/openshift-deployment/lagom/forming-a-cluster.html) that's also useful for the migration guide from LBO to manual deployment so that content should remain.

**Comment by ignasi35** [comment]
🤦🏼‍♂️almost all the content are `include`'s. It'll be easy to redo the lagom page.

**Comment by TimMoore** [comment]
Let's go ahead and target 1.5 now. 1.5.0-RC2 exists and we're not expecting substantial changes before final, unless documentation such as this guide reveals issues.

**Comment by ignasi35** [comment]
On second thought, documenting for 1.4 has the advantage that users migrating out of LBO can first migrate to Lagom 1.4 with this guide and later upgrade to Lagom 1.5.

**Comment by TimMoore** [comment]
I'd say 1.4.x support is a "nice to have" if it doesn't make the guide too confusing to follow, or add extra delays to releasing 1.5.0. The more important thing is making it work with 1.5.0.

**Comment by TimMoore** [comment]
I think we need to get this done before releasing 1.5.0. If we're announcing the guide as part of the Lagom 1.5.0 release, it doesn't make sense to have the guide target 1.4.

**Comment by jroper** [comment]
There's not much to do to upgrade the guide itself to 1.5.0.

**Comment by TimMoore** [comment]
Great, then hopefully it will be no problem to do it before it's released 😄 

Is that something you'll take on @jroper or would you like the team to add it to their pre-release tasks?

**Comment by renatocaval** [comment]
I will work on this. 

I had a quick chat with @jroper about this and we will try to keep a section explaining the minimal steps to have it working for 1.4.0.

**Comment by renatocaval** [comment]
for the record, the Lagom 1.4.0 part of the guide will only contain a section that tells how to add the deps for Akka Management and how to start AkkaManagement and Cluster Bootstrap. All the rest must be exactly the same.

**Comment by marcospereira** [comment]
@renatocaval can this be closed after https://github.com/lightbend/openshift-deployment-guide/pull/42?
