### ISSUE TITLE
Add to techhub guides list

### ISSUE THREAD

**Issue by marcospereira** [lightbend/openshift-deployment-guide#36]
Currently it is not being listed here: https://developer.lightbend.com/guides/

**Comment by TimMoore** [comment]
@jroper is there anything blocking this?

**Comment by jroper** [comment]
That's intentional, the guide technically isn't "published" yet. See https://github.com/lightbend/techhub/pull/247.

**Comment by jroper** [comment]
No, nothing is blocking it.

**Comment by TimMoore** [comment]
I think we should go ahead and publish it if you're happy to

**Comment by jroper** [comment]
The guide currently only includes instructions for Lagom, but does say that it is for Play, Akka and Lagom, and of course that's the intention that those guides will be added. Should the link in the guides page say that it's just for Lagom, for for the Lightbend Platform?

**Comment by TimMoore** [comment]
Yeah, I think both the index and the intro to the guide should only talk about Lagom for now. The intro could say that Play and Akka HTTP guides will be added later.

**Comment by jroper** [comment]
See https://github.com/lightbend/techhub-landing-page/pull/177 and https://github.com/lightbend/techhub/pull/274.
